version: "3.1"

services:
  mongo:
    container_name: fmc-db
    image: mongo:7.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db_data:/data/db
      - ./docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "28017:27017"

volumes:
  db_data:
