-- Trunca as tabelas
TRUNCATE TABLE detalhe_pedidos, pedidos, produtos, categoria, usuarios, pagamentos;

-- INSERIR AS CATEGORIAS
INSERT INTO categoria (nome) VALUES ('Brinquedos');
INSERT INTO categoria (nome) VALUES ('Escolar');
INSERT INTO categoria (nome) VALUES ('DVDs Blu-ray e Livros');
INSERT INTO categoria (nome) VALUES ('Vestuário Infantil');
INSERT INTO categoria (nome) VALUES ('Games');
INSERT INTO categoria (nome) VALUES ('Veículos');
INSERT INTO categoria (nome) VALUES ('Eletrônicos');
INSERT INTO categoria (nome) VALUES ('Playgrounds');
INSERT INTO categoria (nome) VALUES ('Quarto e Decoração');

-- INSERIR OS PRODUTOS
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (1,'Boneco Dinossauro','Espertos como sempre, os Velociraptors são imbatíveis quando o assunto é caçar. Eles estão preparados para se juntar e formar uma equipe de caçadores invencíveis. Com suas garras e ferozes dentes, nada irá parar no caminho destes aterrorizantes dinossauros.',49.8,1,'/assets/img/1.jpg','/assets/img/din/1.jpg',1);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (2,'Mesinha Oficina de Criações','Mesinha Oficina de Criações! Para pintar, montar brinquedos, comer... De ótima qualidade e com acentos e encostos anatômicos que proporcionam maior conforto durante a brincadeira! Peças de fácil encaixe para total segurança das crianças!',130.2,2,'/assets/img/2.jpg','/assets/img/din/2.jpg',6);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (3,'Lancheira','A Lancheira é ideal para acomodar os alimentos, possui garfo, colher e divisória que proporciona praticidade durante a alimentação. A tampa possui um sistema de fechamento seguro e mantém separados os talheres dos alimentos. Produzido em material moderno, que evita a alteração de gosto e odor. É resistente, design moderno e cores alegres.',52.9,2,'/assets/img/3.jpg','/assets/img/din/3.jpg',0);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (4,'Livro Disney Winnie The Pooh - O Livro do Piano de Pooh','É importante que os pequenos tenham contato com a leitura desde a primeira idade. Mesmo que ainda não tenham aprendido a ler, as histórias ajudam a aguçar a curiosidade, estimulam a mente e ensinam o gosto por livros. O Livro do Piano de Pooh também é um livro musical! Vai auxiliar as crianças a desenvolverem a habilidade musical, a coordenação motora e visual! Dessa forma, vão aprender sobre notas musicais ao mesmo tempo que se divertem à beça! Brincadeira rica em aprendizado!',69.9,3,'/assets/img/4.jpg','/assets/img/din/4.jpg',5);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (5,'Boné Fuleco Bebê','Boné Fuleco Bebê – Oficial Copa do Mundo 2014, licenciado pela FIFA mascote brasileiro da Copa do Mundo. No formato da cabeça do Tatu Bola, mascote da Copa com orelhinhas na parte de cima do boné e estampa do rosto do Fuleco para ficar protegido do sol e ainda torcer muito durante os jogos. Parte de trás do boné elástico que se ajusta a cabeça do bebê.',29.9,4,'/assets/img/5.jpg','/assets/img/din/5.jpg',2);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (6,'Camiseta - Infantil - Cinza','A Camiseta de Manga Longa da Disney deixará o seu pequeno ainda mais lindo e estiloso. Na cor mescla claro, em malha penteada, com decote redondo, possui uma estampa para enfeitar ainda mais e fazer de seu pequeno príncipe um verdadeiro anjinho. Não deixe de comprar e proteger o seu pequeno!',45.5,4,'/assets/img/6.jpg','/assets/img/din/6.jpg',4);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (7,'Freakyforms Deluxe: Your Creations, Alive!',' 3DS para povoar seu próprio planeta! Escolha entre mais de 600 combinações diferentes para completar a sua criação, como asas para voar ou rodas. As decisões que você fizer determinarão quais as habilidades do seu Formee e como ele se moverá pelo mundo.',79,5,'/assets/img/7.jpg','/assets/img/din/7.jpg',2);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (8,'Mini Veículo Elétrico - Camaro com Controle Remoto 6V Rosa','Cheio de estilo, o Mini Veículo Camaro Rosa da Bandeirante vai proporcionar muita diversão para os pequenos! Com o Camaro Rosa, a sua pequena vai poder ir pra cima e pra baixo, seja sozinha, seja com a ajuda dos pais. Com o controle remoto os pais também podem participar da brincadeira, movimentando o mini veículo para todos os lados e levando a criança para todo lado.',999.99,6,'/assets/img/8.jpg','/assets/img/din/8.jpg',3);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (9,'Bicicleta Rock - Aro 12 - Azul e Vermelho','A Bicicleta Verden - Rock Aro 12 é ideal para as crianças que estão dando as primeiras pedaladas se divertirem muito e com segurança, pois possui quadro e garfo em aço carbono e rodinhas para pedaladas seguras! É para a garotada que tem energia de sobra e também para os momentos de lazer. Produto certificado por órgão acreditado pelo Inmetro.',149.49,6,'/assets/img/9.jpg','/assets/img/din/9.jpg',9);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (10,'Triciclo','As crianças passam por uma intensa fase de aprendizado durante o crescimento. Há a necessidade de treinar o reflexo, a coordenação motora, de começar a descobrir o mundo ao redor e se aventurar em novas brincadeiras e esportes diferenciados. Pedalar, além de ser uma brincadeira super divertida, vai ajudar a criança a adquirir firmeza nos movimentos das pernas, senso de direção, além de ajudar a vencer medos e a explorar tudo o que há à sua volta!',499.99,6,'/assets/img/10.jpg','/assets/img/din/10.jpg',4);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (11,'DVD Player Compacto','DVD Player Compacto - Disney Aviões da Tectoy! Design super compacto, tematizado com os personagens de Disney Aviões e com função Ripping que permite copiar arquivos de áudio de uma mídia para um pen drive, através da conexão USB! Possui conexão de áudio analógico e estéreo, sistema de alimentação bivolt automático é compatível com as principais mídias do mercado e tem diversas funções de reprodução: Zoom, Multiangulo, Programação, Repetição, entre outros.',172.3,7,'/assets/img/11.jpg','/assets/img/din/11.jpg',6);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (12,'Flat Ball','Jogar bola dentro de casa sem quebrar nada e sujar as paredes é possível! Com a Flat Ball da Multikids, as mães podem ficar despreocupadas com qualquer acidente e as crianças vão se divertir muito com essa brincadeira eletrizante!',114.99,8,'/assets/img/12.jpg','/assets/img/din/12.jpg',5);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (13,'Cama Elástica Galvanizada - 2,50 de Diâmetro','Deixe a brincadeira da criançada ainda mais animada com a Cama Elástica da Jundplay! Ideal para brincadeiras ao ar livre que estimulam a coordenação e movimentação das crianças, a Cama Elástica pode ser usada por crianças com mais de três anos. Estimule a agilidade dos pequenos, deixe a criatividade tomar conta da brincadeira, e gaste toda a energia da criançada nessa deliciosa brincadeira!',1549.99,8,'/assets/img/13.jpg','/assets/img/din/13.jpg',0);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (14,'Porta Objetos Portátil','Com o Porta Objetos Portátil - Spider-Man da Zippy Toys a bagunça no quarto das crianças está com os dias contados! Com este Guarda Brinquedos fica mais fácil e divertido organizar os brinquedos dos pequeninos. Muito práticos, eles vem com tampa retrátil e usam o sistema Pop Up, é só abrir e pronto. Não ocupa espaço depois da brincadeira e é fácil de lavar e guardar, estando sempre disponível para mais brincadeiras! Quando montado, o guarda objetos mede aproximadamente 78 cm de altura e 43 cm de largura.',49.99,9,'/assets/img/14.jpg','/assets/img/din/14.jpg',2);
INSERT INTO produtos (sku,nome,descricao,preco,categoria_id,refe,refebig,quantidade) VALUES (15,'Adesivo de Parede Palhaços - 56x25 cm','Para deixar o quarto dos seus filhos decorado, mais divertido e alegre, com vários personagens dos desenhos e filmes que ele mais gosta é fácil! Depois é só escolher a melhor posição na parede e colá-los! Para removê-los, é bem simples. Eles descolam da parede sem precisar de esforço e não deixam resíduos!',10.9,9,'/assets/img/15.jpg','/assets/img/din/15.jpg',2);

-- SELECIONA 6 PRODUTOS RANDOMICAMENTE
-- E OS ATUALIZA COMO PROMOVIDOS
UPDATE produtos p1
SET promovido = true
FROM (SELECT * FROM produtos ORDER BY random() LIMIT 6) p2
WHERE p1.id = p2.id;
